### ISSUE TITLE
Create a Readme

### ISSUE THREAD

**Issue by kvprashant** [bipinu/chaakri#1]
Should consist of what this is about and how to setup development environment

**Comment by bipinu** [comment]
Aah yes. Johnny and I currently use Asana for managing chaakri,  and the task is assigned to me. 
I guess we'll move task management to GitHub as well.

**Comment by kvprashant** [comment]
If the setup instructions comes here, then the testing can go on and issues raised and classified as features. Of course all after the bare minimum comes up.

**Comment by bipinu** [comment]
Assigned to myself

**Comment by bipinu** [comment]
Added a basic readme. Let me know if anything's vague or incorrect.
