### ISSUE TITLE
Downgrade to Bootstrap to v2.x

### ISSUE THREAD

**Issue by bipinu** [bipinu/chaakri#2]

**Comment by tulsid** [comment]
@bipinu Should we downgrade or perhaps just fix the problem in 3? What is the actual problem?

**Comment by bipinu** [comment]
Since v3 is still in beta, I thought we might downgrade to v2.
However, I'm alright with whatever you decide. By the time we are ready with chaakri, Bootstrap v3 should be stable as well.

**Comment by tulsid** [comment]
I'd suggest plug in latest. If there are specific issues we can fix them. Sure v3 will be released soon :)

**Comment by bipinu** [comment]
Cool! Closing this then :-)

**Comment by kvprashant** [comment]
I am around if there's a bug from bootstrap in v3. Always wanted starter projects on open frameworks!

**Comment by tulsid** [comment]
Nice! @bipinu, once you have it plugged in let us know and we can give it a whirl.

**Comment by bipinu** [comment]
V3 is already plugged in and committed. You can create tasks, like modal view for details, etc, and assign to yourself. Let me know if you need help with anything.
