### ISSUE TITLE
User drop down on header doesn't close 

### ISSUE THREAD

**Issue by bipinu** [bipinu/chaakri#8]

**Comment by nisarul** [comment]
Fixed Dropdown issue. Now the dropdown on header closes.

**Comment by bipinu** [comment]
Nisar,
Quick question. You didn't modify bootstrap css file, right? That's not advisable.

**Comment by nisarul** [comment]
I modified bootstrap.min.css 
There was no other way of making the dropdown close.

**Comment by bipinu** [comment]
You should never edit external libraries. Next time you update them, all your changed would be lost. 
You can add the same css rule to our css file.

**Comment by bipinu** [comment]
Fixed!
